version: '3.3'

services:
  postgres:
    container_name: voting-app-postgres
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      LANG: en_US.utf8
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  redis:
    container_name: voting-app-redis
    image: redis:7.2.2-alpine
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  vote:
    container_name: voting-app-vote
    build:
      context: .
      dockerfile: Dockerfile-vote
    volumes:
      - ./.env:/code/.env
    depends_on:
      - redis
    healthcheck:
      test: curl --fail http://vote:8080 || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
  
  worker:
    container_name: voting-app-worker
    build:
      context: .
      dockerfile: Dockerfile-worker
    volumes:
      - ./.env:/App/.env
    depends_on:
      - postgres
      - redis

  result:
    container_name: voting-app-result
    build:
      context: .
      dockerfile: Dockerfile-result
    volumes:
      - ./.env:/usr/app/.env
    depends_on:
      - postgres
    healthcheck:
      test: curl --fail http://result:8888 || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
  
  nginx:
    container_name: voting-app-nginx
    image: nginx:1.25.3
    ports:
      - '${PORT}:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vote
      - result
    healthcheck:
      test: curl --fail http://nginx:80 || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

volumes:
  postgres-data: {}
  redis:
    driver: local