version: '3.8'

services:
  postgres:
    container_name: voting-app-postgres
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      LANG: en_US.utf8
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: voting-app-redis
    image: redis:7.2.2-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  vote:
    container_name: voting-app-vote
    build:
      context: .
      dockerfile: Dockerfile-vote
    ports:
      - 4567:8080
    depends_on:
      - redis
  
  worker:
    container_name: voting-app-worker
    build:
      context: .
      dockerfile: Dockerfile-worker
    depends_on:
      - postgres
      - redis

  result:
    container_name: voting-app-result
    build:
      context: .
      dockerfile: Dockerfile-result
    ports:
      - 5678:8888
    depends_on:
      - postgres

  nginx:
    container_name: voting-app-nginx
    image: nginx:1.25.3-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # vault-server:
  #   container_name: voting-app-vault-server
  #   image: vault:1.13.3
  #   ports:
  #     - "8200:8200"
  #   environment:
  #     VAULT_ADDR: "http://0.0.0.0:8200"
  #     VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
  #   cap_add:
  #     - IPC_LOCK


volumes:
  postgres-data: {}
  redis:
    driver: local