FROM python:3.11-alpine3.17

WORKDIR /code

COPY ./src/vote/requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./src/vote .

CMD ["python", "app.py"]
